name: fyp_savr
description: "Savr App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Updated SDK constraint for modern packages


dependencies:
  flutter:
    sdk: flutter

  # Firebase Dependencies (Latest Stable Versions)
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.1.0
  cloud_functions: ^5.1.0

  # UI & Navigation
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_maps_flutter: ^2.2.6
  geolocator: ^9.0.2

  # Media & Files
  image_picker: ^1.1.2
  fl_chart: ^0.68.0 # Updated to a recent version
  intl: ^0.19.0
  file_picker: ^8.0.3
  path_provider: ^2.1.3
  open_file: ^3.3.2


  # Network & APIs
  http: ^1.2.1
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.1.2 # Corrected from invalid version
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.2
  jose: ^0.3.5
  crypto: ^3.0.3

  # Authentication
  google_sign_in: ^6.2.1 # Corrected from invalid version
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # Fonts
  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-VariableFont_wght.ttf
  
  assets:
    - assets/fonts/
    - assets/img/savrlogo.png
    - assets/img/google_logo.png
